import { createHash } from 'node:crypto';

import type { ReleaseMarker } from './types.js';

const MARKER_PATTERN = /<!--\s*gitea-release-please:\s*(\{[^\r\n]*\})\s*-->/;

export function hashContent(content: string): string {
  return createHash('sha256').update(content, 'utf8').digest('hex');
}

export function serializeMarker(marker: ReleaseMarker): string {
  return `<!-- gitea-release-please: ${JSON.stringify(marker)} -->`;
}

export function parseMarker(body: string): ReleaseMarker | null {
  const match = body.match(MARKER_PATTERN);
  if (!match?.[1]) return null;

  try {
    const candidate: unknown = JSON.parse(match[1]);
    if (!isMarker(candidate)) return null;
    return candidate;
  } catch {
    return null;
  }
}

function isMarker(value: unknown): value is ReleaseMarker {
  if (!value || typeof value !== 'object') return false;
  const marker = value as Partial<ReleaseMarker>;
  const fileHashes = marker.fileHashes;
  if (
    marker.schema !== 1 ||
    typeof marker.version !== 'string' ||
    typeof marker.tagName !== 'string' ||
    typeof marker.targetBranch !== 'string' ||
    typeof marker.changelogPath !== 'string' ||
    typeof marker.releaseNotesPath !== 'string' ||
    !fileHashes ||
    typeof fileHashes !== 'object'
  ) {
    return false;
  }
  const changelogHash = fileHashes[marker.changelogPath];
  const releaseNotesHash = fileHashes[marker.releaseNotesPath];
  return (
    typeof changelogHash === 'string' &&
    /^[0-9a-f]{64}$/.test(changelogHash) &&
    typeof releaseNotesHash === 'string' &&
    /^[0-9a-f]{64}$/.test(releaseNotesHash)
  );
}

export function buildPullRequestBody(marker: ReleaseMarker, releaseNotes: string): string {
  return `${serializeMarker(marker)}\n\n${releaseNotes.trim()}\n\n---\nThis PR was generated by Gitea Release Please.`;
}
